/**
 * @druumen/sessions-db — public TypeScript entry point.
 *
 * This file is HAND-CRAFTED and committed to the repo (not regenerated by
 * `tsc`). The `tsc` build emits per-source-file declarations as `.d.mts`
 * (because the sources are `.mjs`); this `.d.ts` curates the public type
 * surface so cockpit-class consumers can write:
 *
 *     import type {
 *       KnownSession,
 *       Projection,
 *       SessionEvent,
 *       ActivityState,
 *       Outcome,
 *     } from '@druumen/sessions-db';
 *
 * and resolve everything through one entry — without having to memorise
 * which lib/* file each typedef lives in.
 *
 * The `lib/index.mjs` runtime entry is intentionally a Day-1 stub
 * (re-exports happen on Day 3 — once the public *function* surface is
 * settled). This `.d.ts` is safe to ship today because it is types-only
 * and has zero runtime side effects.
 *
 * Convention for tsc-emitted neighbours:
 *   - Auto-generated:     `types/<name>.d.mts`  (mirrors `lib/<name>.mjs`)
 *   - Hand-crafted:       `types/index.d.ts`    (this file)
 *
 * `package.json` `"types"` points at `./types/index.d.ts` so this is the
 * resolution entry. The neighbouring `.d.mts` files exist for direct
 * sub-path imports (`@druumen/sessions-db/lib/storage.d.mts`) but cockpit
 * should prefer this curated surface for forward compat.
 */

// ---------------------------------------------------------------------------
// Type vocabulary — re-exported from `lib/types.d.mts` (which `tsc` lifted
// from the `@typedef` block in `lib/types.mjs`). This is the canonical
// surface for cockpit consumers.
// ---------------------------------------------------------------------------

export type {
  // Branded scalars
  SessionStableId,
  ClaudeSessionId,
  EventId,
  Iso8601,
  // Enums
  ActivityState,
  Outcome,
  IdentitySource,
  IdentityConfidence,
  EventOp,
  // Composite shapes
  TranscriptFile,
  IdentityResolution,
  ParentCandidate,
  KnownSession,
  ProjectionMeta,
  Projection,
  SessionEvent,
} from './types.d.mts';

// ---------------------------------------------------------------------------
// Function signatures — re-exported from per-source `.d.mts` neighbours.
//
// We re-export TYPES of functions (typeof) rather than the runtime symbols
// because Day 2 keeps `lib/index.mjs` a runtime stub. Day 3 will flip
// `lib/index.mjs` into a real re-export hub and at that point `tsc` will
// regenerate `types/index.d.mts` with the same shape — but consumers who
// imported through this `.d.ts` see no breakage because the type names
// are identical.
//
// The `typeof import(...)` pattern is the standard TypeScript ambient
// re-export when the source is JS-with-JSDoc.
// ---------------------------------------------------------------------------

// uuid.mjs
export type GenerateSessionId = typeof import('./uuid.d.mts').generateSessionId;
export type IsSessionId = typeof import('./uuid.d.mts').isSessionId;
export type ExtractTimestamp = typeof import('./uuid.d.mts').extractTimestamp;

// projection.mjs
export type ApplyEvent = typeof import('./projection.d.mts').applyEvent;
export type EmptyProjection = typeof import('./projection.d.mts').emptyProjection;
export type EmptySession = typeof import('./projection.d.mts').emptySession;
export type RebuildFromEvents = typeof import('./projection.d.mts').rebuildFromEvents;

// storage.mjs
export type NewEvent = typeof import('./storage.d.mts').newEvent;
export type AppendEvent = typeof import('./storage.d.mts').appendEvent;
export type ReadAllEvents = typeof import('./storage.d.mts').readAllEvents;
export type LoadProjection = typeof import('./storage.d.mts').loadProjection;
export type SaveProjection = typeof import('./storage.d.mts').saveProjection;
export type RebuildProjection = typeof import('./storage.d.mts').rebuildProjection;
export type TryUpdateProjection = typeof import('./storage.d.mts').tryUpdateProjection;
export type RecordSessionSeen = typeof import('./storage.d.mts').recordSessionSeen;

// identity.mjs
export type ResolveIdentity = typeof import('./identity.d.mts').resolveIdentity;
export type FindByClaudeSessionId = typeof import('./identity.d.mts').findByClaudeSessionId;
export type FindByTranscriptLineage = typeof import('./identity.d.mts').findByTranscriptLineage;
export type ScanFingerprintCandidates = typeof import('./identity.d.mts').scanFingerprintCandidates;
export type CollectParentCandidates = typeof import('./identity.d.mts').collectParentCandidates;
export type CapParentCandidates = typeof import('./identity.d.mts').capParentCandidates;
export type ClassifyCorroborators = typeof import('./identity.d.mts').classifyCorroborators;
export type MeetsThreshold = typeof import('./identity.d.mts').meetsThreshold;

// sweep.mjs
export type ComputeSweepTransitions = typeof import('./sweep.d.mts').computeSweepTransitions;
export type ComputeEffectiveLastProgress = typeof import('./sweep.d.mts').computeEffectiveLastProgress;

// sanitize.mjs
export type SanitizeFirstPrompt = typeof import('./sanitize.d.mts').sanitizeFirstPrompt;
export type StripSystemReminders = typeof import('./sanitize.d.mts').stripSystemReminders;
export type StripIdeWrappers = typeof import('./sanitize.d.mts').stripIdeWrappers;

// transcript.mjs
export type ParseTranscriptFile = typeof import('./transcript.d.mts').parseTranscriptFile;
export type ListTranscriptFiles = typeof import('./transcript.d.mts').listTranscriptFiles;
export type WorkspaceHashFromCwd = typeof import('./transcript.d.mts').workspaceHashFromCwd;

// git-context.mjs
export type GitContextFn = typeof import('./git-context.d.mts').gitContext;

// paths.mjs (Day 4 — storage path resolution chain)
export type ResolveStoragePaths = typeof import('./paths.d.mts').resolveStoragePaths;
export type PathsFromRoot = typeof import('./paths.d.mts').pathsFromRoot;
